// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdqaykJfJSDx6xABAqwqG6b-qQfPGZNV0',
    appId: '1:339950476603:web:a947d5d309545defd96b1e',
    messagingSenderId: '339950476603',
    projectId: 'newflutter-e039c',
    authDomain: 'newflutter-e039c.firebaseapp.com',
    storageBucket: 'newflutter-e039c.appspot.com',
    measurementId: 'G-BMVZ0R2F10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRaJ_nHiIQI58UfnMNzxzaHHh_Hhz_XSM',
    appId: '1:339950476603:android:17992a1579056561d96b1e',
    messagingSenderId: '339950476603',
    projectId: 'newflutter-e039c',
    storageBucket: 'newflutter-e039c.appspot.com',
  );
}
